#!/usr/bin/env python

import sys
import os
import re
from subprocess import Popen, call, PIPE, STDOUT
import glob

p = Popen('date', stdout=PIPE, stdin=PIPE,
                     stderr=STDOUT)
DATE = p.stdout.read().decode('utf-8').strip()

PELICAN_ROOT = os.path.expanduser(os.getenv('PELICAN_ROOT'))
PELICAN_CONTENT = os.path.expanduser(os.getenv('PELICAN_CONTENT'))

EDITOR = os.getenv('EDITOR')

FILE_EXTENSION = ".md"

if not PELICAN_ROOT:
    print("You should set PELICAN_ROOT env variable.")
    exit(1)

if not PELICAN_CONTENT:
    print("You should set PELICAN_CONTENT env variable.")
    exit(2)

ls = Popen(f'ls {PELICAN_CONTENT}/*.md', shell=True, stdout=PIPE, stdin=PIPE,
           stderr=PIPE)
lst = ls.communicate()[0]
ls.stdout.close()

pre_lst = lst.decode('utf-8').strip().split('\n')
new_lst = "\n".join([path.split('/')[-1] for path in pre_lst
                     if path.endswith(FILE_EXTENSION)]).encode('utf-8')

fzf = Popen('fzf', shell=True, stdin=PIPE, stdout=PIPE)
output, err = fzf.communicate(input=new_lst)

filename = output.decode('utf-8').strip()
filepath = f"{PELICAN_CONTENT}/{filename}"

print(filename, filepath)
call([EDITOR, filepath])

do_post = input('Commit and push changes, thus modifying'
                'the `modified\' date? (N/y) ')

if do_post in ('y', 'Y'):

    modified_line = int()

    with open(filepath, 'r') as post:
        post_data = post.readlines()

    for idx, line in enumerate(post_data):
        if line.startswith('modified:'):
            post_data[idx] = f'modified: {DATE}\n'
            break

    post_date_modified = "".join(post_data)

    with open(filepath, 'w') as post:
        post.write(post_date_modified)

    os.chdir(PELICAN_ROOT)
    call(['./build.sh'])
