#!/usr/bin/env python

import os
from plumbum import local

PELICAN_CONTENT = os.path.expanduser(os.getenv('PELICAN_CONTENT'))
local.cwd.chdir(PELICAN_CONTENT)

GIT = local['git']

def git_repost():
    adding = GIT['add', '.']()
    print(adding)

    commiting = GIT['commit', '-a', '-m', 'autocommit']()
    print(commiting)

    pushing = GIT['push']()
    print(pushing)

if __name__ == "__main__":
    git_repost()